### ISSUE TITLE
Orde-codering - stap3b: definitie orde-codering

### ISSUE THREAD

**Issue by jorenvo10** [Sweco-NL/generator_drainage_units#20]

**Comment by harm-nomden-sweco** [comment]
Twee mogelijkheden zijn nu opgenomen:

1. Iedere branch van hydroobjecten (tot iedere splitsing) krijgt een opeenvolgende nummer (1, 2, 3, ...). Beginnend bij de hoofdtak vanuit het uitstroompunt. Zijtakken tellen mee en krijgen ook een opeenvolgend nummer (branch hoofdtak 1, zijtak 2, branch hoofdtak 3, zijtak 4, branch hoofdtak 5, etc.  
![image](https://github.com/user-attachments/assets/8dbef355-4265-4568-9c3e-2edcf61c9aa3)

2. De hoofdtak is opgeknipt in stukken vanwege de instroompunten van c-watergangen. Ieder deel van de hoofdtak krijgt een opvolgend nummer. Zijtakken van hydroobjecten krijgen ook een nummer. c-watergangen behoren qua code bij het deel waarmee het het uitstroompunt deelt. 
![image](https://github.com/user-attachments/assets/ca04fa79-cf14-4efe-85da-42ac679449cb)
